### ISSUE TITLE
Are the bash file for processing WMH and ATLAS-V2 available? 

### ISSUE THREAD

**Issue by bakerhassan** [FinnBehrendt/Mahalanobis-Unsupervised-Anomaly-Detection#3]
I know that the preprocessing files do exist in previous repos, but I would appreciate it if you upload the new scripts for the new dataset and any updates for the old ones :)

Thank you,

**Comment by FinnBehrendt** [comment]
Hi,

Apologies for overlooking the WMH and ATLAS preprocessing scripts! I’ve decided to upload the processed data directly to ensure consistency, avoiding any differences caused by non-deterministic processing steps.
You can find the data [here](https://1drv.ms/u/c/66229029a9e95461/EVb21X1kmXxCh_xfqMNmzH8B1Rqe_wWDHYzoQuiGj94k3Q?e=wjFP6h) (approximately 37GB): 
Please let me know if you run into any issues!
